CREATE SCHEMA `NYCGreenTaxi` ;
use NYCGreenTaxi;

CREATE TABLE D_VENDOR(
  D_VENDOR_KEY int(10) NOT NULL,
  D_VENDOR varchar(50),
  UPDATE_DATE datetime,
  PRIMARY KEY (D_VENDOR_KEY)
);

CREATE TABLE D_RATE_CODE(
  D_RATE_CODE_KEY int(10) NOT NULL,
  D_RATE varchar(50),
  UPDATE_DATE datetime,
  PRIMARY KEY (D_RATE_CODE_KEY)
);

CREATE TABLE D_PAYMENT_TYPE(
  D_PAYMENT_TYPE_KEY int(10) NOT NULL,
  D_PAYMENT_TYPE varchar(15),
  UPDATE_DATE datetime,
  PRIMARY KEY (D_PAYMENT_TYPE_KEY)
);

CREATE TABLE D_TRIP_DATE(
  D_TRIP_DATE_KEY int(10) NOT NULL,
  D_TRIP_DATE date,
  UPDATE_DATE datetime,
  PRIMARY KEY (D_TRIP_DATE_KEY)
);

CREATE TABLE D_TRIP_TIME(
  D_TRIP_TIME_KEY int(10) NOT NULL,
  D_TRIP_TIME time,
  UPDATE_DATE datetime,
  PRIMARY KEY (D_TRIP_TIME_KEY)
);

CREATE TABLE D_TRIP_TYPE(
  D_TRIP_TYPE_KEY int(10) NOT NULL,
  D_TRIP_TYPE varchar(15),
  UPDATE_DATE datetime,
  PRIMARY KEY (D_TRIP_TYPE_KEY)
);

CREATE TABLE FACT_NYC_GREENTAXI_TRIP (
    FNGT_KEY int(10) NOT NULL,  
    D_VENDOR_KEY int(10) NOT NULL,  
    D_PICKUP_DATE_KEY int(10) NOT NULL,
    D_DROPOFF_DATE_KEY int(10) NOT NULL,
    D_PICKUP_TIME_KEY int(10) NOT NULL,
	D_DROPOFF_TIME_KEY int(10) NOT NULL,
    D_RATE_CODE_KEY int(10) NOT NULL,  
    D_PAYMENT_TYPE_KEY int(10) NOT NULL,
    D_TRIP_TYPE_KEY int(10) NOT NULL,
	PASSENGER_COUNT int(10) NOT NULL,
    PICKUP_TRIP_LATITUDE decimal(15, 10),
    PICKUP_TRIP_LONGTITUDE decimal(15, 10),
	DROPOFF_TRIP_LATITUDE decimal(15, 10),
    DROPOFF_TRIP_LONGTITUDE decimal(15, 10),
    TRIP_DISTANCE decimal(10,2) NOT NULL,
    FARE_AMOUNT decimal(10,2) NOT NULL,
    EXTRA_AMOUNT decimal(10,2) NOT NULL,
    MTA_TAX_AMOUNT decimal(10,2) NOT NULL,
    TIP_AMOUNT decimal(10,2) NOT NULL,
    TOLL_AMOUNT decimal(10,2) NOT NULL,
	IMPROVEMENT_SURCHARGE_AMOUNT decimal(10,2) NOT NULL,
    TOTAL_AMOUNT decimal(10,2) NOT NULL,
    TRIP_DURATION int(10) NOT NULL,
    UPDATE_DATE  date,  
    PRIMARY KEY (FNGT_KEY));



